# nixpacks.toml
[phases.setup]
nixPkgs = ['python311', 'python311Packages.virtualenv']

[phases.install]
cmds = [
  'python3 -m venv venv && . venv/bin/activate && pip install --upgrade pip && pip install -r requirements.txt'
]
ports = ["5002"]
[start]
cmd = '. venv/bin/activate && python run.py'
